rr-cache: Update cache for packaging
Signed-off-by: Intel Next Project <intel-next-maintainers@eclists.intel.com>

diff --git a/eywa/merge_ci/rr-cache/0421f74bf598bbdd898451737b0fef09a8e86504/postimage b/eywa/merge_ci/rr-cache/0421f74bf598bbdd898451737b0fef09a8e86504/postimage
--- a/eywa/merge_ci/rr-cache/0421f74bf598bbdd898451737b0fef09a8e86504/postimage
+++ b/eywa/merge_ci/rr-cache/0421f74bf598bbdd898451737b0fef09a8e86504/postimage
@@ -114,22 +114,22 @@ nextrpm-pkg:
 # Deb target
 # ---------------------------------------------------------------------------
 quiet_cmd_builddeb = BUILDDEB
-        cmd_builddeb = set -e; \
-        test `id -u` = 0 || \
-        test -n "$(KBUILD_PKG_ROOTCMD)" || { \
-                which fakeroot >/dev/null 2>&1 && \
-                KBUILD_PKG_ROOTCMD="fakeroot -u"; \
-        } || { \
-                echo; \
-                echo "builddeb must be run as root (or using fakeroot)."; \
-                echo "KBUILD_PKG_ROOTCMD is unset and fakeroot not found."; \
-                echo "Try setting KBUILD_PKG_ROOTCMD to a command to acquire"; \
-                echo "root privileges (e.g., 'fakeroot -u' or 'sudo')."; \
-                false; \
-        } && \
-        \
-        $$KBUILD_PKG_ROOTCMD $(CONFIG_SHELL) \
-                $(srctree)/scripts/package/builddeb $@
+	cmd_builddeb = set -e; \
+	test `id -u` = 0 || \
+	test -n "$(KBUILD_PKG_ROOTCMD)" || { \
+		which fakeroot >/dev/null 2>&1 && \
+		KBUILD_PKG_ROOTCMD="fakeroot -u"; \
+	} || { \
+		echo; \
+		echo "builddeb must be run as root (or using fakeroot)."; \
+		echo "KBUILD_PKG_ROOTCMD is unset and fakeroot not found."; \
+		echo "Try setting KBUILD_PKG_ROOTCMD to a command to acquire"; \
+		echo "root privileges (e.g., 'fakeroot -u' or 'sudo')."; \
+		false; \
+	} && \
+	\
+	$$KBUILD_PKG_ROOTCMD $(CONFIG_SHELL) \
+		$(srctree)/scripts/package/builddeb $@
 
 PHONY += deb-pkg
 deb-pkg:
